export const designTokens = {
  color: {
    primary: "#0057b8",
    primaryStrong: "#004494",
    success: "#00a859",
    danger: "#d92d20",
    warning: "#d97706",
    backgroundMain: "#ffffff",
    backgroundSubtle: "#f6f9fd",
    card: "#ffffff",
    textMain: "#0f172a",
    textMuted: "#536273",
    border: "#dbe6f3",
    money: "#0f3a66",
  },
  font: {
    sans: '"Monteras", "Inter", Arial, sans-serif',
    mono: '"Courier New", Courier, monospace',
  },
  fontSize: {
    titleLarge: "32px",
    titleSmall: "20px",
    body: "16px",
    button: "16px",
    note: "14px",
  },
  spacing: {
    1: "4px",
    2: "8px",
    3: "12px",
    4: "16px",
    6: "24px",
    8: "32px",
  },
  radius: {
    card: "20px",
    button: "14px",
    input: "14px",
    badge: "999px",
  },
};
