CREATE TABLE KyThiDua (
  id VARCHAR(64) PRIMARY KEY,
  tenKy NVARCHAR(255) NOT NULL,
  loaiKy NVARCHAR(50) NOT NULL,
  ngayBatDau DATE NOT NULL,
  ngayKetThuc DATE NOT NULL,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE NhomTieuChiThiDua (
  id VARCHAR(64) PRIMARY KEY,
  tenNhom NVARCHAR(255) NOT NULL,
  moTa NVARCHAR(1000),
  thuTuHienThi INT NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TieuChiThiDua (
  id VARCHAR(64) PRIMARY KEY,
  nhomId VARCHAR(64) NOT NULL,
  tenTieuChi NVARCHAR(255) NOT NULL,
  moTa NVARCHAR(1000),
  diemToiDa DECIMAL(10,2) NOT NULL DEFAULT 10,
  trongSo DECIMAL(10,2) NOT NULL DEFAULT 1,
  cachChamDiem NVARCHAR(1000),
  coCanMinhChung BIT NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (nhomId) REFERENCES NhomTieuChiThiDua(id)
);

CREATE TABLE GiaTriConNguoi (
  id VARCHAR(64) PRIMARY KEY,
  maGiaTri VARCHAR(100) NOT NULL UNIQUE,
  tenGiaTri NVARCHAR(255) NOT NULL,
  moTa NVARCHAR(1000),
  hanhViNenCo NVARCHAR(MAX),
  hanhViCanTranh NVARCHAR(MAX),
  diemToiDa DECIMAL(10,2) NOT NULL DEFAULT 10,
  coCanMinhChung BIT NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PhieuDanhGiaThiDua (
  id VARCHAR(64) PRIMARY KEY,
  kyThiDuaId VARCHAR(64) NOT NULL,
  nhanVienId VARCHAR(64) NOT NULL,
  teamId VARCHAR(64) NOT NULL,
  diemCongViec DECIMAL(10,2) NOT NULL DEFAULT 0,
  diemChatLuong DECIMAL(10,2) NOT NULL DEFAULT 0,
  diemGiaTriConNguoi DECIMAL(10,2) NOT NULL DEFAULT 0,
  diemCongVanHoa DECIMAL(10,2) NOT NULL DEFAULT 0,
  diemCanNhacNho DECIMAL(10,2) NOT NULL DEFAULT 0,
  diemCuoiCung DECIMAL(10,2) NOT NULL DEFAULT 0,
  xepLoai NVARCHAR(50),
  nhanXetNhanVien NVARCHAR(MAX),
  nhanXetTruongNhom NVARCHAR(MAX),
  deXuatCaiThien NVARCHAR(MAX),
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (kyThiDuaId) REFERENCES KyThiDua(id)
);

CREATE TABLE ChiTietDanhGiaThiDua (
  id VARCHAR(64) PRIMARY KEY,
  phieuDanhGiaId VARCHAR(64) NOT NULL,
  tieuChiId VARCHAR(64) NOT NULL,
  diemNhanVienTuCham DECIMAL(10,2),
  diemTruongNhomCham DECIMAL(10,2),
  diemDuocDuyet DECIMAL(10,2),
  ghiChuNhanVien NVARCHAR(MAX),
  ghiChuTruongNhom NVARCHAR(MAX),
  minhChungUrl NVARCHAR(1000),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (phieuDanhGiaId) REFERENCES PhieuDanhGiaThiDua(id),
  FOREIGN KEY (tieuChiId) REFERENCES TieuChiThiDua(id)
);

CREATE TABLE GhiNhanHanhVi (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  nguoiGhiNhanId VARCHAR(64) NOT NULL,
  teamId VARCHAR(64) NOT NULL,
  kyThiDuaId VARCHAR(64) NOT NULL,
  giaTriConNguoiId VARCHAR(64) NOT NULL,
  loaiGhiNhan NVARCHAR(100) NOT NULL,
  tieuDe NVARCHAR(255) NOT NULL,
  noiDung NVARCHAR(MAX),
  mucAnhHuong NVARCHAR(50) NOT NULL,
  diemDeXuat DECIMAL(10,2) NOT NULL DEFAULT 0,
  diemDuocDuyet DECIMAL(10,2) NOT NULL DEFAULT 0,
  minhChungUrl NVARCHAR(1000),
  phanHoiNhanVien NVARCHAR(MAX),
  nhanXetTruongNhom NVARCHAR(MAX),
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (kyThiDuaId) REFERENCES KyThiDua(id),
  FOREIGN KEY (giaTriConNguoiId) REFERENCES GiaTriConNguoi(id)
);

CREATE TABLE KeHoachCaiThien (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  teamId VARCHAR(64) NOT NULL,
  kyThiDuaId VARCHAR(64) NOT NULL,
  vanDeCanCaiThien NVARCHAR(MAX) NOT NULL,
  nguyenNhanDuKien NVARCHAR(MAX),
  hanhDongCaiThien NVARCHAR(MAX),
  nguoiHoTroId VARCHAR(64),
  thoiHanHoanThanh DATE,
  ketQuaSauCaiThien NVARCHAR(MAX),
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (kyThiDuaId) REFERENCES KyThiDua(id)
);

CREATE TABLE XepHangThiDua (
  id VARCHAR(64) PRIMARY KEY,
  kyThiDuaId VARCHAR(64) NOT NULL,
  nhanVienId VARCHAR(64) NOT NULL,
  teamId VARCHAR(64) NOT NULL,
  hang INT NOT NULL,
  diemCuoiCung DECIMAL(10,2) NOT NULL,
  xepLoai NVARCHAR(50) NOT NULL,
  ghiNhanNoiBat NVARCHAR(MAX),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (kyThiDuaId) REFERENCES KyThiDua(id)
);
