CREATE TABLE TamNhin (
  id VARCHAR(64) PRIMARY KEY,
  noiDung NVARCHAR(MAX) NOT NULL,
  phienBan NVARCHAR(50) NOT NULL,
  ngayHieuLuc DATE NOT NULL,
  nguoiCapNhatId VARCHAR(64),
  trangThai NVARCHAR(50) NOT NULL,
  ghiChu NVARCHAR(MAX),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SuMenh (
  id VARCHAR(64) PRIMARY KEY,
  noiDung NVARCHAR(MAX) NOT NULL,
  yNghiaKhachHang NVARCHAR(MAX),
  yNghiaNhanVien NVARCHAR(MAX),
  yNghiaXaHoi NVARCHAR(MAX),
  phienBan NVARCHAR(50) NOT NULL,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MucTieuNam (
  id VARCHAR(64) PRIMARY KEY,
  tenMucTieu NVARCHAR(255) NOT NULL,
  lyDoChon NVARCHAR(MAX),
  nhomMucTieu NVARCHAR(100) NOT NULL,
  chiSoDo NVARCHAR(255),
  ketQuaMongMuon NVARCHAR(MAX),
  nguoiPhuTrachId VARCHAR(64),
  teamId VARCHAR(64),
  thoiHan DATE,
  tienDo DECIMAL(10,2) NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MucTieuQuy (
  id VARCHAR(64) PRIMARY KEY,
  mucTieuNamId VARCHAR(64) NOT NULL,
  tenMucTieuQuy NVARCHAR(255) NOT NULL,
  ketQuaCanDat NVARCHAR(MAX),
  nguoiPhuTrachId VARCHAR(64),
  teamId VARCHAR(64),
  tienDo DECIMAL(10,2) NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  ghiChuRuiRo NVARCHAR(MAX),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (mucTieuNamId) REFERENCES MucTieuNam(id)
);

CREATE TABLE MucTieuThang (
  id VARCHAR(64) PRIMARY KEY,
  mucTieuQuyId VARCHAR(64) NOT NULL,
  tenMucTieuThang NVARCHAR(255) NOT NULL,
  ketQuaCanDat NVARCHAR(MAX),
  viecTrongTam NVARCHAR(MAX),
  nguoiPhuTrachId VARCHAR(64),
  teamId VARCHAR(64),
  tienDo DECIMAL(10,2) NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (mucTieuQuyId) REFERENCES MucTieuQuy(id)
);

CREATE TABLE ViecTrongTam (
  id VARCHAR(64) PRIMARY KEY,
  mucTieuNamId VARCHAR(64),
  mucTieuQuyId VARCHAR(64),
  mucTieuThangId VARCHAR(64),
  tenViecTrongTam NVARCHAR(255) NOT NULL,
  nguoiPhuTrachId VARCHAR(64),
  teamId VARCHAR(64),
  khachHangId VARCHAR(64),
  taskId VARCHAR(64),
  thoiHan DATE,
  mucQuanTrong NVARCHAR(50) NOT NULL,
  tienDo DECIMAL(10,2) NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE KetQuaCongViec (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  teamId VARCHAR(64) NOT NULL,
  tongViec INT NOT NULL DEFAULT 0,
  viecHoanThanh INT NOT NULL DEFAULT 0,
  viecDungHan INT NOT NULL DEFAULT 0,
  viecTreHan INT NOT NULL DEFAULT 0,
  viecLamLai INT NOT NULL DEFAULT 0,
  tongGioThucTe DECIMAL(10,2) NOT NULL DEFAULT 0,
  diemKetQuaCongViec DECIMAL(10,2) NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DanhGiaHelpdesk (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  teamId VARCHAR(64) NOT NULL,
  ticketId VARCHAR(64),
  nguyenNhan NVARCHAR(100),
  diemHelpdesk DECIMAL(10,2) NOT NULL DEFAULT 0,
  leaderDuyet NVARCHAR(50) NOT NULL,
  ghiChu NVARCHAR(MAX),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GhiNhanDongGop (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  nguoiGhiNhanId VARCHAR(64),
  loaiGhiNhan NVARCHAR(100) NOT NULL,
  noiDungNganGon NVARCHAR(MAX),
  minhChungUrl NVARCHAR(1000),
  diemDeXuat DECIMAL(10,2) NOT NULL DEFAULT 0,
  diemDuocDuyet DECIMAL(10,2) NOT NULL DEFAULT 0,
  leaderDuyet NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DiemCanCaiThien (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  noiDungCanCaiThien NVARCHAR(MAX) NOT NULL,
  nguyenNhan NVARCHAR(MAX),
  mucAnhHuong NVARCHAR(50),
  huongKhacPhuc NVARCHAR(MAX),
  thoiHanCaiThien DATE,
  nguoiHoTroId VARCHAR(64),
  trangThai NVARCHAR(50) NOT NULL,
  leaderDuyet NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BangCong (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  thang NVARCHAR(20) NOT NULL,
  ngayCongChuan DECIMAL(10,2) NOT NULL,
  ngayCongThucTe DECIMAL(10,2) NOT NULL,
  diTre INT NOT NULL DEFAULT 0,
  veSom INT NOT NULL DEFAULT 0,
  nghiPhep DECIMAL(10,2) NOT NULL DEFAULT 0,
  nghiKhongPhep DECIMAL(10,2) NOT NULL DEFAULT 0,
  lamViecBenNgoai DECIMAL(10,2) NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CauHinhLuong3P (
  id VARCHAR(64) PRIMARY KEY,
  nhom NVARCHAR(100) NOT NULL,
  tenThietLap NVARCHAR(255),
  giaTri NVARCHAR(MAX),
  dieuKienApDung NVARCHAR(MAX),
  nguoiDuyetId VARCHAR(64),
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BangLuong (
  id VARCHAR(64) PRIMARY KEY,
  kyLuong NVARCHAR(20) NOT NULL,
  nhanVienId VARCHAR(64) NOT NULL,
  teamId VARCHAR(64),
  luongTheoViTri DECIMAL(18,2) NOT NULL DEFAULT 0,
  luongTheoNangLuc DECIMAL(18,2) NOT NULL DEFAULT 0,
  luongTheoKetQua DECIMAL(18,2) NOT NULL DEFAULT 0,
  thuong DECIMAL(18,2) NOT NULL DEFAULT 0,
  phuCap DECIMAL(18,2) NOT NULL DEFAULT 0,
  phucLoi DECIMAL(18,2) NOT NULL DEFAULT 0,
  khoanGiamTru DECIMAL(18,2) NOT NULL DEFAULT 0,
  tongThuNhap DECIMAL(18,2) NOT NULL DEFAULT 0,
  thucNhan DECIMAL(18,2) NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
