CREATE TABLE ThietBiNhanVien (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  tenThietBi NVARCHAR(255) NOT NULL,
  maThietBi NVARCHAR(100) NOT NULL,
  heDieuHanh NVARCHAR(100),
  loaiThietBi NVARCHAR(100),
  trangThai NVARCHAR(50) NOT NULL,
  ngayKichHoat DATE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PhienHoatDong (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  thietBiId VARCHAR(64) NOT NULL,
  thoiGianBatDau DATETIME NOT NULL,
  thoiGianKetThuc DATETIME,
  tongThoiLuong INT NOT NULL DEFAULT 0,
  tongThoiGianHoatDong INT NOT NULL DEFAULT 0,
  tongThoiGianKhongHoatDong INT NOT NULL DEFAULT 0,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UngDungSuDung (
  id VARCHAR(64) PRIMARY KEY,
  phienHoatDongId VARCHAR(64),
  nhanVienId VARCHAR(64) NOT NULL,
  thietBiId VARCHAR(64) NOT NULL,
  tenUngDung NVARCHAR(255) NOT NULL,
  tenCuaSo NVARCHAR(500),
  phanLoai NVARCHAR(100) NOT NULL,
  thoiGianBatDau DATETIME NOT NULL,
  thoiGianKetThuc DATETIME,
  tongThoiLuong INT NOT NULL DEFAULT 0,
  coLienQuanCongViec BIT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE WebsiteSuDung (
  id VARCHAR(64) PRIMARY KEY,
  phienHoatDongId VARCHAR(64),
  nhanVienId VARCHAR(64) NOT NULL,
  thietBiId VARCHAR(64) NOT NULL,
  domain NVARCHAR(255) NOT NULL,
  url NVARCHAR(1000),
  tieuDeTab NVARCHAR(500),
  phanLoai NVARCHAR(100) NOT NULL,
  thoiGianBatDau DATETIME NOT NULL,
  thoiGianKetThuc DATETIME,
  tongThoiLuong INT NOT NULL DEFAULT 0,
  coLienQuanCongViec BIT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BmsPageTracking (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  thietBiId VARCHAR(64),
  sessionId VARCHAR(128),
  route NVARCHAR(500) NOT NULL,
  tenManHinh NVARCHAR(255),
  thoiGianVao DATETIME NOT NULL,
  thoiGianRoi DATETIME,
  tongThoiLuong INT NOT NULL DEFAULT 0,
  soLanTuongTac INT NOT NULL DEFAULT 0,
  coTaoDuLieu BIT NOT NULL DEFAULT 0,
  coCapNhatDuLieu BIT NOT NULL DEFAULT 0,
  coHoanTatThaoTac BIT NOT NULL DEFAULT 0,
  coLoiThaoTac BIT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BmsFeatureEvent (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  sessionId VARCHAR(128),
  route NVARCHAR(500) NOT NULL,
  tenTinhNang NVARCHAR(255) NOT NULL,
  loaiSuKien NVARCHAR(100) NOT NULL,
  doiTuongLienQuan NVARCHAR(100),
  doiTuongId VARCHAR(64),
  thoiDiem DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata NVARCHAR(MAX),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TaskActivityTracking (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  taskId VARCHAR(64) NOT NULL,
  khachHangId VARCHAR(64),
  thoiGianMoTask DATETIME,
  thoiGianDongTask DATETIME,
  tongThoiLuong INT NOT NULL DEFAULT 0,
  soLanCapNhat INT NOT NULL DEFAULT 0,
  soComment INT NOT NULL DEFAULT 0,
  soFileDinhKem INT NOT NULL DEFAULT 0,
  coHoanThanhTask BIT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CanhBaoHoatDong (
  id VARCHAR(64) PRIMARY KEY,
  nhanVienId VARCHAR(64) NOT NULL,
  teamId VARCHAR(64),
  loaiCanhBao NVARCHAR(255) NOT NULL,
  noiDungCanhBao NVARCHAR(MAX),
  duLieuGoc NVARCHAR(MAX),
  mucDo NVARCHAR(50) NOT NULL,
  ghiChuLeader NVARCHAR(MAX),
  trangThaiXuLy NVARCHAR(50) NOT NULL,
  ngayPhatSinh DATE NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CauHinhTheoDoiHoatDong (
  id VARCHAR(64) PRIMARY KEY,
  tenCauHinh NVARCHAR(255) NOT NULL,
  theoDoiUngDung NVARCHAR(50) NOT NULL,
  theoDoiWebsite NVARCHAR(50) NOT NULL,
  theoDoiTrongBMS NVARCHAR(50) NOT NULL,
  batCanhBaoBatThuong NVARCHAR(50) NOT NULL,
  idleThresholdMinutes INT NOT NULL DEFAULT 15,
  thoiGianLuuDuLieuNgay INT NOT NULL DEFAULT 90,
  choNhanVienXemDuLieu BIT NOT NULL DEFAULT 1,
  duaVaoThiDua NVARCHAR(100) NOT NULL,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ChinhSachDuLieuNoiBo (
  id VARCHAR(64) PRIMARY KEY,
  tenChinhSach NVARCHAR(255) NOT NULL,
  noiDung NVARCHAR(MAX) NOT NULL,
  phienBan NVARCHAR(50) NOT NULL,
  ngayHieuLuc DATE NOT NULL,
  trangThai NVARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
